DATA CLASS;
	SET SASHELP.CLASS;

PROC SORT DATA=CLASS;
 	BY DESCENDING AGE;
 	
PROC PRINT DATA=CLASS;

PROC PLOT DATA=CLASS;
	PLOT HEIGHT*AGE="*"/
	VAXIS= 50 TO 75 BY 2.5;

PROC UNIVARIATE DATA=CLASS;
	VAR AGE;
	
PROC MEANS DATA=CLASS SUM MEAN VAR;
	VAR HEIGHT;
RUN;